apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: mikrolab
  namespace: mikrolab
  annotations:
    argocd.argoproj.io/instance: mikrolab
  labels:
    app.kubernetes.io/name: mikrolab
    app.kubernetes.io/instance: mikrolab
    app.kubernetes.io/component: infrastructure
    app.kubernetes.io/part-of: mikrolab

spec:
  schema:
    apiVersion: v1alpha1
    kind: MikroLab
    spec:
   
      env: string | default="staging" enum="staging,production"

      ingress:
        class: string | default="traefik" enum="traefik"
 
      certmanager:
        enabled: boolean | default=true
        provider: string | default="duckdns" enum="duckdns,cloudflare"
        domain: string  
        email: string  

  resources:

    - id: createNamespace
      template:
        apiVersion: v1
        kind: Namespace
        metadata:
          name: cert-manager
          # annotations:
          #   argocd.argoproj.io/tracking-id: ${schema.metadata.?annotations["argocd.argoproj.io/tracking-id"]}


    - id: certManagerBundle
      includeWhen:
        - ${schema.spec.certmanager.enabled}
      template:
          apiVersion: kro.run/v1alpha1
          kind: CertManagerBundle
          metadata:
            name: cert-manager-bundle
            namespace: cert-manager
            annotations:
              # argocd.argoproj.io/tracking-id: ${schema.metadata.?annotations["argocd.argoproj.io/tracking-id"]}
              argocd.argoproj.io/instance: cert-manager-bundle
          spec:
            env: ${schema.spec.env}
            ingress:
              requests: true

            tls:
              enabled: true
              email: ${schema.spec.certmanager.email}
              provider: ${schema.spec.certmanager.provider}
              domain: ${schema.spec.certmanager.domain}
              dynamic: ${schema.spec.certmanager.provider == "duckdns"}

    - id: ingressRequestConfigMap
      externalRef:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: ingress-request-configmap
          namespace: cert-manager


    # - id: giteaConfig
    #   template:
    #     apiVersion: kro.run/v1alpha1
    #     kind: GiteaConfig
    #     metadata:
    #       name: gitea

    #     spec:
    #       env: staging
    #       domain: cloudbreaker.me
    #       actions: true
    #       mirrors:
    #         - https://codeberg.org/eddiemoya/docker.git
    #         - https://codeberg.org/eddiemoya/resourcegraphdefinitions.git
    #         - https://codeberg.org/eddiemoya/charts.git
    #         - https://codeberg.org/eddiemoya/rr7-mikrolab-template.git






    # - id: homepageChart
    #   template:
    #     apiVersion: kro.run/v1alpha1
    #     kind: HomepageChart
    #     metadata:
    #       name: homepage
    #       namespace: argocd
    #       annotations:
    #         # argocd.argoproj.io/tracking-id: ${schema.metadata.?annotations["argocd.argoproj.io/tracking-id"]}
    #         argocd.argoproj.io/instance: homepage-chart
    #     spec:
    #       env: ${schema.spec.env}
    #       chart: homepage
  
    # - id: argocdIngressRequest
    #   template:
    #       apiVersion: kro.run/v1alpha1
    #       kind: IngressRequest
    #       metadata:
    #         name: argocd
    #         namespace: argocd
    #         annotations:
    #           argocd.argoproj.io/instance: argocd-ingress
    #           # argocd.argoproj.io/tracking-id: ${schema.metadata.?annotations["argocd.argoproj.io/tracking-id"]}        
    #       spec:
    #         env: ${schema.spec.env}
    #         subdomain: argocd
    #         service:
    #           name: argocd-server


    # - id: headlampIngressRequest
    #   template:
    #       apiVersion: kro.run/v1alpha1
    #       kind: IngressRequest
    #       metadata:
    #         name: headlamp
    #         namespace: kube-system
    #         annotations:
    #           # argocd.argoproj.io/tracking-id: ${schema.metadata.?annotations["argocd.argoproj.io/tracking-id"]}
    #           argocd.argoproj.io/instance: headlamp     
    #       spec:
    #         env: ${schema.spec.env}
    #         subdomain: headlamp
    #         service:
    #           name: headlamp
    #           port: 80
  
  
    # - id: giteaIngressRequest
    #   template:
    #       apiVersion: kro.run/v1alpha1
    #       kind: IngressRequest
    #       metadata:
    #         name: gitea
    #         namespace: gitea
    #         annotations:
    #           argocd.argoproj.io/instance: gitea         
    #       spec:
    #         env: ${schema.spec.env}
    #         subdomain: git
    #         service:
    #           name: gitea-http
    #           port: 3000

