apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: headlamp-chart
  annotations:
    argocd.argoproj.io/instance: headlamp-chart
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  schema:
    apiVersion: v1alpha1
    kind: HeadlampChart
    spec:
      chart: string | default="headlamp" enum="headlamp"
      env: string | default="staging" enum="staging,production"


  resources:
    - id: headlampChart
      # readyWhen:
      #   - ${homepageChart.status.condition.status}
      template:
        apiVersion: kro.run/v1alpha1
        kind: Argofile
        metadata:
          name: headlamp
          namespace: argocd

        spec:
          applications: 

            # Future plans:
            ## Make these generic and move them into a file a gitgenerator can pull, with everything disabled by default
            ## Then use the list generator to merge with instance spec that overrides any default values. 
            ## Each chart can be enabled by setting enabled: true for that named item. 
            - name: headlamp
              enabled: true
              hook: PreSync
              sync:
                createNamespace: true
              destination:
                namespace: headlamp
              source:
                # repoURL: oci://ghcr.io/m0nsterrr/helm-charts/homepage
                # path: .
                # targetRevision: 4.1.4
                repoURL: https://kubernetes-sigs.github.io/headlamp/
                chart: headlamp
                targetRevision: 0.34.0


    - id: headlampIngressRequest
      template:
          apiVersion: kro.run/v1alpha1
          kind: IngressRequest
          metadata:
            name: headlamp
            namespace: headlamp
            annotations:
              argocd.argoproj.io/instance: headlamp
              argocd.argoproj.io/tracking-id: ${schema.metadata.?annotations["argocd.argoproj.io/tracking-id"]}        
          spec:
            env: ${schema.spec.env}
            subdomain: headlamp
            service:
              name: headlamp
